name: Scheduled Main.js Execution

on:
  schedule:
    - cron: "0 4,7,10,13,16 * * *" # Runs every hour at 10am, 1pm, 4pm, 7pm and 10pm
  workflow_dispatch:  # Allows manual trigger
permissions:
  actions: read  # Change to write if needed
  contents: read
  security-events: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust the version if needed

      - name: Install Dependencies
        run: npm install  # Change this if using yarn or pnpm

      - name: Inject Secrets into Environment
        run: |
          echo "URLS=${{ secrets.URLS }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "API_KEY is set: ${#API_KEY}"  # Check if API_KEY exists
          echo "MONGODB_URI is set: ${#MONGODB_URI}"  # Check if MongoDB URI exists

      - name: Run main.js
        run: node main.js
        env:
          URLS: ${{ secrets.URLS }}
          API_KEY: ${{ secrets.API_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
